language: perl
perl:
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.16"

env: PERL_CPANM_OPT="--verbose --notest --force --skip-satisfied"

before_install:
    - sudo apt-get install -y libidn11-dev
    - cpanm Devel::CheckLib Module::Install Module::Install::XSUtil
    - git clone --depth=1 --branch=$TRAVIS_BRANCH https://github.com/zonemaster/zonemaster-ldns.git
    - cpanm ./zonemaster-ldns
    - rm -rf zonemaster-ldns

install:
    - cpanm --installdeps .

script:
    - perl Makefile.PL
    - make test
