name: CI

on:
  push:
    branches:
      - develop
      - master
      - 'releases/**'
  pull_request:
    branches:
      - develop
      - master
      - 'releases/**'

jobs:
  run-tests:
    strategy:
      matrix:
        runner:
          - ubuntu-20.04
        perl:
          - '5.32'
          - '5.30'
          - '5.28'
          - '5.26'
          - '5.16'

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v2

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: Dependencies
        env:
          PERL5LIB: /usr/share/perl5:${{ env.PERL5LIB }}
        run: |
          sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            cpanminus \
            gettext \
            libidn11-dev \
            libssl-dev \
            libtool \
            m4 \

          cpanm --notest Module::Install
          cpanm --notest --installdeps .

      - name: Show content of log files
        if: ${{ failure() }}
        run: cat /home/runner/.cpanm/work/*/build.log

      - name: Install
        env:
          PERL5LIB: /usr/share/perl5:${{ env.PERL5LIB }}
        run: |
          cpanm --verbose --notest .

      - name: Test
        env:
          PERL5LIB: /usr/share/perl5:${{ env.PERL5LIB }}
        run: |
          prove -lv
